# Redis ����
spring:
  redis:
    #    Redis ��������ַ
    host: 127.0.0.1
    #    �˿�
    port: 6379
    #    ���ݿ�����
    database: 0
    #    ���ӳ�ʱʱ�䣨���룩
    timeout: 1800000
    lettuce:
      pool:
        #        ���ӳ������������������ʾû�����ƣ�
        max-active: 20
        #        ��������ȴ�ʱ�䣨������ʾû�����ƣ�
        max-wait: -1
        #        ���ӳ�������������
        max-idle: 5
        #        ���ӳ�ֵ��С��������
        min-idle: 0